services:
  music_server:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - rabbitmq
    env_file:
      - .env

  worker:
    build: .
    container_name: 'worker'
    command: celery -A src.infrastructure.background_tasks.app.celery_app worker --loglevel=INFO
    env_file:
      - .env
    depends_on:
      - minio
      - rabbitmq

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      retries: 10
      start_period: 10s

  rabbitmq:
    image: rabbitmq:4.2.3-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: ${S3_USER}
      MINIO_ROOT_PASSWORD: ${S3_PASSWORD}
      USE_SSL: false
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  pgdata:
  rabbitmq:
  minio_data:
