"""Add track model

Revision ID: 90f2c9b9fe70
Revises: 5d8b7287f473
Create Date: 2026-02-21 17:01:14.885247

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '90f2c9b9fe70'
down_revision: Union[str, Sequence[str], None] = '5d8b7287f473'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('track',
    sa.Column('track_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('audio_key', sa.String(), nullable=False),
    sa.Column('image_key', sa.String(), nullable=False),
    sa.Column('release_fk', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['release_fk'], ['release.release_id'], ),
    sa.PrimaryKeyConstraint('track_id'),
    sa.UniqueConstraint('audio_key'),
    sa.UniqueConstraint('image_key'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('track')
    # ### end Alembic commands ###
