"""Add release model

Revision ID: 96a95d2cd99e
Revises: 4a7ff52a68b5
Create Date: 2026-02-18 03:23:09.078331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96a95d2cd99e'
down_revision: Union[str, Sequence[str], None] = '4a7ff52a68b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('release',
    sa.Column('release_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('author_fk', sa.Uuid(), nullable=False),
    sa.Column('genre_fk', sa.Uuid(), nullable=False),
    sa.Column('realease_data', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_fk'], ['author.author_id'], ),
    sa.ForeignKeyConstraint(['genre_fk'], ['genre.genre_id'], ),
    sa.PrimaryKeyConstraint('release_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('release')
    # ### end Alembic commands ###
