"""Upd track model

Revision ID: 988ba191b4ab
Revises: 90f2c9b9fe70
Create Date: 2026-02-21 23:14:34.881410

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '988ba191b4ab'
down_revision: Union[str, Sequence[str], None] = '90f2c9b9fe70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('track', 'duration',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('track', 'audio_key',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('track', 'image_key',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('track', 'image_key',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('track', 'audio_key',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('track', 'duration',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
