"""Add release type field

Revision ID: c0da2d5c0d91
Revises: 96a95d2cd99e
Create Date: 2026-02-18 23:35:02.764210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c0da2d5c0d91'
down_revision: Union[str, Sequence[str], None] = '96a95d2cd99e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('release', sa.Column('release_date', sa.DateTime(), nullable=False))
    op.add_column('release', sa.Column('release_type', sa.String(), nullable=False))
    op.drop_column('release', 'realease_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('release', sa.Column('realease_data', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('release', 'release_type')
    op.drop_column('release', 'release_data')
    # ### end Alembic commands ###
