"""Change track fields

Revision ID: fb68117123a2
Revises: 988ba191b4ab
Create Date: 2026-02-26 23:50:02.464088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb68117123a2'
down_revision: Union[str, Sequence[str], None] = '988ba191b4ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('track_image_key_key'), 'track', type_='unique')
    op.drop_constraint(op.f('track_title_key'), 'track', type_='unique')
    op.drop_column('track', 'image_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track', sa.Column('image_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('track_title_key'), 'track', ['title'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('track_image_key_key'), 'track', ['image_key'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
